filter:
    excluded_paths:
        - '3rdparty/*'
        - 'js/3rdparty/*'

imports:
    - javascript
    - php

tools:
    external_code_coverage: 
        timeout: 7200    # Timeout in seconds. 120 minutes

